set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)

execute_process(COMMAND /usr/bin/xcrun --find clang
  OUTPUT_VARIABLE AIRDCCORE_APPLE_CLANG OUTPUT_STRIP_TRAILING_WHITESPACE
  COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND /usr/bin/xcrun --find clang++
  OUTPUT_VARIABLE AIRDCCORE_APPLE_CLANGXX OUTPUT_STRIP_TRAILING_WHITESPACE
  COMMAND_ERROR_IS_FATAL ANY)

set(CMAKE_C_COMPILER "${AIRDCCORE_APPLE_CLANG}" CACHE FILEPATH "Apple Clang C compiler")
set(CMAKE_CXX_COMPILER "${AIRDCCORE_APPLE_CLANGXX}" CACHE FILEPATH "Apple Clang C++ compiler")
set(CMAKE_OSX_SYSROOT macosx CACHE STRING "macOS SDK")
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "Supported architecture")
set(CMAKE_OSX_DEPLOYMENT_TARGET 14.0 CACHE STRING "Discovery deployment target")
