function(airdcpp_adapt_leveldb_snappy)
  if(NOT TARGET leveldb::leveldb)
    message(FATAL_ERROR "leveldb::leveldb target is required for the LevelDB Snappy adapter")
  endif()
  if(NOT TARGET Snappy::snappy)
    message(FATAL_ERROR "Snappy::snappy target is required for the LevelDB Snappy adapter")
  endif()

  get_target_property(leveldb_link_items leveldb::leveldb INTERFACE_LINK_LIBRARIES)
  if(leveldb_link_items STREQUAL "leveldb_link_items-NOTFOUND")
    set(leveldb_link_items)
  endif()

  set(repaired_link_items)
  set(plain_snappy_count 0)
  foreach(link_item IN LISTS leveldb_link_items)
    if(link_item STREQUAL "snappy")
      math(EXPR plain_snappy_count "${plain_snappy_count} + 1")
      list(APPEND repaired_link_items Snappy::snappy)
    else()
      list(APPEND repaired_link_items "${link_item}")
    endif()
  endforeach()

  if(NOT plain_snappy_count EQUAL 1)
    message(FATAL_ERROR
      "leveldb::leveldb expected exactly one plain snappy item; found ${plain_snappy_count}")
  endif()

  set_property(TARGET leveldb::leveldb PROPERTY
    INTERFACE_LINK_LIBRARIES "${repaired_link_items}")
endfunction()

function(airdcpp_adapt_reproducible_leveldb)
  if(NOT TARGET leveldb::leveldb)
    message(FATAL_ERROR "LevelDB imported target was not discovered by upstream")
  endif()
  # Check all direct LevelDB paths belong to LevelDB, rather than merely some
  # declared component. Both generic and configuration-specific exports count.
  get_target_property(configurations leveldb::leveldb IMPORTED_CONFIGURATIONS)
  if("${configurations}" MATCHES "-NOTFOUND$")
    set(configurations)
  endif()
  list(APPEND configurations NOCONFIG DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
  list(REMOVE_DUPLICATES configurations)
  set(properties IMPORTED_LOCATION INTERFACE_INCLUDE_DIRECTORIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES)
  foreach(configuration IN LISTS configurations)
    string(TOUPPER "${configuration}" configuration)
    list(APPEND properties "IMPORTED_LOCATION_${configuration}"
      "INTERFACE_INCLUDE_DIRECTORIES_${configuration}" "INTERFACE_SYSTEM_INCLUDE_DIRECTORIES_${configuration}")
  endforeach()
  set(location_found FALSE)
  foreach(property IN LISTS properties)
    get_target_property(items leveldb::leveldb "${property}")
    if("${items}" MATCHES "-NOTFOUND$")
      continue()
    endif()
    foreach(item IN LISTS items)
      airdcpp_classify_dependency_path("${item}" category normalized)
      if(NOT category STREQUAL "component:leveldb")
        message(FATAL_ERROR "LevelDB provenance must resolve under AIRDCCORE_LEVELDB_PREFIX: ${item}")
      endif()
      if(property MATCHES "^IMPORTED_LOCATION")
        set(location_found TRUE)
      endif()
    endforeach()
  endforeach()
  if(NOT location_found)
    message(FATAL_ERROR "LevelDB provenance requires an imported archive location")
  endif()
  # Audit the transitive interface first, allowing only the one repairable plain
  # name. The established adapter checks that there is exactly one such item.
  set(AIRDCCORE_CHECK_UNREPAIRED_LEVELDB TRUE)
  set_property(GLOBAL PROPERTY AIRDCCORE_RESOLUTION_ROWS "")
  set_property(GLOBAL PROPERTY AIRDCCORE_RESOLUTION_VISITED "")
  airdcpp_walk_dependency_target(leveldb::leveldb)
  get_target_property(link_items leveldb::leveldb INTERFACE_LINK_LIBRARIES)
  set(reference_count 0)
  set(plain_count 0)
  foreach(item IN LISTS link_items)
    if(item STREQUAL snappy)
      math(EXPR plain_count "${plain_count} + 1")
    endif()
    if(item STREQUAL snappy OR item STREQUAL "Snappy::snappy" OR
        item STREQUAL "$<LINK_ONLY:Snappy::snappy>")
      math(EXPR reference_count "${reference_count} + 1")
    endif()
  endforeach()
  if(NOT plain_count EQUAL 1)
    message(FATAL_ERROR "leveldb::leveldb expected exactly one plain snappy item; found ${plain_count}")
  endif()
  if(NOT reference_count EQUAL 1)
    message(FATAL_ERROR "LevelDB expected exactly one Snappy reference")
  endif()
  airdcpp_adapt_leveldb_snappy()
endfunction()

function(airdcpp_define_system_iconv system_iconv_library)
  if(NOT IS_ABSOLUTE "${system_iconv_library}")
    message(FATAL_ERROR "system Iconv library must be absolute")
  endif()
  if(IS_SYMLINK "${system_iconv_library}")
    message(FATAL_ERROR "system Iconv library must not be a symlink")
  endif()
  if(NOT EXISTS "${system_iconv_library}" OR IS_DIRECTORY "${system_iconv_library}")
    message(FATAL_ERROR "system Iconv library must be a regular file: ${system_iconv_library}")
  endif()
  if(TARGET AirDCCore::SystemIconv)
    message(FATAL_ERROR "AirDCCore::SystemIconv target already exists")
  endif()

  add_library(AirDCCore::SystemIconv INTERFACE IMPORTED GLOBAL)
  set_property(TARGET AirDCCore::SystemIconv PROPERTY
    INTERFACE_LINK_LIBRARIES "${system_iconv_library}")
endfunction()
