function(airdcpp_require_apple_clang)
  if(NOT CMAKE_C_COMPILER_ID STREQUAL "AppleClang" OR
      NOT CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    message(FATAL_ERROR
      "Apple Clang is required; got C=${CMAKE_C_COMPILER_ID}, CXX=${CMAKE_CXX_COMPILER_ID}")
  endif()
endfunction()

# This allowlist is intentionally explicit; /usr/local and /usr/lib are not
# dependency roots. SDK and toolchain files must resolve inside Apple's roots.
function(airdcpp_classify_dependency_path path category_out normalized_out)
  if(NOT IS_ABSOLUTE "${path}" OR "${path}" MATCHES "[\t\n\r;]" OR
      NOT EXISTS "${path}")
    message(FATAL_ERROR "undeclared dependency path: ${path}")
  endif()
  file(REAL_PATH "${path}" physical)
  set(owners)
  foreach(component IN ITEMS bzip2 zlib openssl miniupnpc leveldb libmaxminddb snappy boost)
    string(TOUPPER "${component}" upper)
    set(prefix "${AIRDCCORE_${upper}_PREFIX}")
    if(NOT IS_ABSOLUTE "${prefix}" OR NOT IS_DIRECTORY "${prefix}" OR IS_SYMLINK "${prefix}")
      message(FATAL_ERROR "invalid declared component prefix: ${component}")
    endif()
    file(REAL_PATH "${prefix}" prefix)
    cmake_path(IS_PREFIX prefix "${physical}" NORMALIZE owned)
    if(owned)
      list(APPEND owners "${component}")
      file(RELATIVE_PATH relative "${prefix}" "${physical}")
      set(normalized "$PREFIX/${component}")
      if(NOT relative STREQUAL "")
        string(APPEND normalized "/${relative}")
      endif()
    endif()
  endforeach()
  list(LENGTH owners count)
  if(count EQUAL 1)
    list(GET owners 0 component)
    set(category "component:${component}")
  elseif(count GREATER 1)
    message(FATAL_ERROR "dependency path has multiple declared owners: ${path}")
  else()
    set(category)
    foreach(root_kind IN ITEMS SDK TOOLCHAIN)
      if(root_kind STREQUAL SDK)
        set(apple_root "${CMAKE_OSX_SYSROOT}")
      else()
        set(apple_root "${AIRDCCORE_APPLE_TOOLCHAIN_ROOT}")
      endif()
      if(IS_ABSOLUTE "${apple_root}" AND IS_DIRECTORY "${apple_root}")
        file(REAL_PATH "${apple_root}" apple_root)
        cmake_path(IS_PREFIX apple_root "${physical}" NORMALIZE apple_owned)
        if(apple_owned)
          file(RELATIVE_PATH relative "${apple_root}" "${physical}")
          set(category apple-system)
          set(normalized "$${root_kind}/${relative}")
          break()
        endif()
      endif()
    endforeach()
    if(NOT category)
      message(FATAL_ERROR "undeclared dependency path: ${path}")
    endif()
  endif()
  set(${category_out} "${category}" PARENT_SCOPE)
  set(${normalized_out} "${normalized}" PARENT_SCOPE)
endfunction()

function(airdcpp_resolution_item target property item)
  if("${item}" MATCHES "[\t\n\r]")
    message(FATAL_ERROR "unsafe imported target property: ${target}.${property}")
  endif()
  if(property MATCHES "^INTERFACE_COMPILE_OPTIONS($|_)")
    if(item STREQUAL "-Werror" OR item STREQUAL "-Wthread-safety" OR item STREQUAL "-pthread")
      set(category reviewed-compile-option)
      set(normalized "${item}")
    elseif("${item}" MATCHES "\\$<")
      message(FATAL_ERROR "unsafe generator expression: ${item}")
    else()
      message(FATAL_ERROR "unreviewed compile option: ${target}.${property}: ${item}")
    endif()
  elseif(property MATCHES "(^IMPORTED_(LOCATION|IMPLIB)|INCLUDE_DIRECTORIES|^INTERFACE_(LINK_DIRECTORIES|SOURCES)($|_))")
    airdcpp_classify_dependency_path("${item}" category normalized)
  elseif(TARGET "${item}")
    set(category target)
    set(normalized "${item}")
    airdcpp_walk_dependency_target("${item}")
  elseif("${item}" MATCHES "^\\$<LINK_ONLY:([A-Za-z0-9_.:+-]+)>$")
    # Classify this one reviewed expression without evaluating CMake content.
    set(dependency "${CMAKE_MATCH_1}")
    if(NOT TARGET "${dependency}")
      message(FATAL_ERROR "unsafe generator expression: ${item}")
    endif()
    set(category generator-target)
    set(normalized "${item}")
    airdcpp_walk_dependency_target("${dependency}")
  elseif("${item}" MATCHES "\\$<")
    message(FATAL_ERROR "unsafe generator expression: ${item}")
  elseif(IS_ABSOLUTE "${item}")
    airdcpp_classify_dependency_path("${item}" category normalized)
  elseif(target STREQUAL "Threads::Threads" AND
      (item STREQUAL "-pthread" OR item STREQUAL "-lpthread" OR item STREQUAL "pthread"))
    set(category apple-thread-toolchain)
    set(normalized "${item}")
  elseif(target STREQUAL "leveldb::leveldb" AND item STREQUAL snappy AND
      AIRDCCORE_CHECK_UNREPAIRED_LEVELDB)
    # The caller checks the exact count and provenance before repairing it.
    return()
  else()
    message(FATAL_ERROR "unreviewed plain linker item: ${target}.${property}: ${item}")
  endif()
  set_property(GLOBAL APPEND PROPERTY AIRDCCORE_RESOLUTION_ROWS
    "${target}\t${property}\t${category}\t${normalized}")
endfunction()

function(airdcpp_walk_dependency_target target)
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "required dependency target is missing: ${target}")
  endif()
  get_property(visited GLOBAL PROPERTY AIRDCCORE_RESOLUTION_VISITED)
  if("${target}" IN_LIST visited)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY AIRDCCORE_RESOLUTION_VISITED "${target}")
  get_target_property(imported "${target}" IMPORTED)
  if(NOT imported)
    message(FATAL_ERROR "dependency target is not imported: ${target}")
  endif()
  get_target_property(type "${target}" TYPE)
  set_property(GLOBAL APPEND PROPERTY AIRDCCORE_RESOLUTION_ROWS
    "${target}\tTYPE\ttarget\t${type}")
  get_target_property(configurations "${target}" IMPORTED_CONFIGURATIONS)
  if("${configurations}" MATCHES "-NOTFOUND$")
    set(configurations)
  endif()
  list(APPEND configurations NOCONFIG DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
  list(REMOVE_DUPLICATES configurations)
  set(properties IMPORTED_LOCATION IMPORTED_IMPLIB INTERFACE_INCLUDE_DIRECTORIES
    INTERFACE_SYSTEM_INCLUDE_DIRECTORIES INTERFACE_LINK_LIBRARIES INTERFACE_LINK_OPTIONS
    INTERFACE_COMPILE_OPTIONS INTERFACE_LINK_DIRECTORIES INTERFACE_SOURCES
    IMPORTED_LINK_INTERFACE_LIBRARIES IMPORTED_LINK_DEPENDENT_LIBRARIES)
  set(base_properties "${properties}")
  foreach(configuration IN LISTS configurations)
    string(TOUPPER "${configuration}" configuration)
    if(NOT configuration MATCHES "^[A-Z0-9_]+$")
      message(FATAL_ERROR "unsafe imported configuration: ${target}: ${configuration}")
    endif()
    foreach(property IN LISTS base_properties)
      list(APPEND properties "${property}_${configuration}")
    endforeach()
  endforeach()
  foreach(property IN LISTS properties)
    get_target_property(items "${target}" "${property}")
    if("${items}" MATCHES "-NOTFOUND$")
      continue()
    endif()
    foreach(item IN LISTS items)
      if(NOT "${item}" STREQUAL "")
        airdcpp_resolution_item("${target}" "${property}" "${item}")
      endif()
    endforeach()
  endforeach()
endfunction()

function(airdcpp_record_dependency_resolution output)
  set_property(GLOBAL PROPERTY AIRDCCORE_RESOLUTION_ROWS "")
  set_property(GLOBAL PROPERTY AIRDCCORE_RESOLUTION_VISITED "")
  foreach(target IN LISTS ARGN)
    airdcpp_walk_dependency_target("${target}")
  endforeach()
  get_property(rows GLOBAL PROPERTY AIRDCCORE_RESOLUTION_ROWS)
  list(REMOVE_DUPLICATES rows)
  list(SORT rows)
  file(WRITE "${output}" "target\tproperty\tclassification\tvalue\n")
  foreach(row IN LISTS rows)
    file(APPEND "${output}" "${row}\n")
  endforeach()
endfunction()

function(airdcpp_require_value name actual expected)
  if(NOT "${actual}" STREQUAL "${expected}")
    message(FATAL_ERROR "${name} must be ${expected}; got ${actual}")
  endif()
endfunction()

function(airdcpp_apply_source_prefix_map target source replacement)
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "source prefix-map target does not exist: ${target}")
  endif()
  if(NOT IS_ABSOLUTE "${source}")
    message(FATAL_ERROR "source prefix-map source must be absolute: ${source}")
  endif()
  if("${source}" MATCHES "[;\n\r]" OR
      "${replacement}" STREQUAL "" OR
      IS_ABSOLUTE "${replacement}" OR
      "${replacement}" MATCHES "[;\n\r]")
    message(FATAL_ERROR "invalid source prefix-map: ${source}=${replacement}")
  endif()
  target_compile_options("${target}" PRIVATE
    "-ffile-prefix-map=${source}=${replacement}")
endfunction()

function(airdcpp_record_target target output)
  set(target_exists FALSE)
  set(target_type "")
  set(target_imported_location "")
  set(target_imported_configurations "")
  set(target_include_directories "")
  set(target_interface_libraries "")

  if(TARGET "${target}")
    set(target_exists TRUE)
    get_target_property(target_type "${target}" TYPE)
    get_target_property(target_imported_location "${target}" IMPORTED_LOCATION)
    get_target_property(target_imported_configurations "${target}" IMPORTED_CONFIGURATIONS)
    get_target_property(target_include_directories "${target}" INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(target_interface_libraries "${target}" INTERFACE_LINK_LIBRARIES)

    foreach(property_variable IN ITEMS
        target_type
        target_imported_location
        target_imported_configurations
        target_include_directories
        target_interface_libraries)
      if("${${property_variable}}" MATCHES "-NOTFOUND$")
        set(${property_variable} "")
      endif()
    endforeach()
  endif()

  file(APPEND "${output}"
    "target.name=${target}\n"
    "target.exists=${target_exists}\n"
    "target.type=${target_type}\n"
    "target.imported_location=${target_imported_location}\n"
    "target.imported_configurations=${target_imported_configurations}\n"
    "target.include_directories=${target_include_directories}\n"
    "target.interface_libraries=${target_interface_libraries}\n")

  # Many package configs specify only configuration-specific library locations.
  set(recorded_configurations "${target_imported_configurations}")
  list(REMOVE_DUPLICATES recorded_configurations)
  list(SORT recorded_configurations)
  foreach(configuration IN LISTS recorded_configurations)
    string(TOUPPER "${configuration}" configuration)
    get_target_property(configuration_location "${target}"
      "IMPORTED_LOCATION_${configuration}")
    if("${configuration_location}" MATCHES "-NOTFOUND$")
      set(configuration_location "")
    endif()
    file(APPEND "${output}"
      "target.imported_location.${configuration}=${configuration_location}\n")
  endforeach()
endfunction()
function(airdcpp_define_core_version_command)
  if(NOT CMAKE_GENERATOR STREQUAL "Ninja")
    message(FATAL_ERROR "controlled Core version requires Ninja")
  endif()
  foreach(required AIRDCCORE_STAGED_SOURCE_DIR AIRDCCORE_VERSION_AUTHORITY
      AIRDCCORE_VERSION_AUTHORITY_SHA256 AIRDCCORE_VERSION_ADAPTER PYTHON_EXECUTABLE)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
      message(FATAL_ERROR "missing controlled Core version authority: ${required}")
    endif()
  endforeach()
  file(SHA256 "${AIRDCCORE_VERSION_AUTHORITY}" actual_authority)
  if(NOT actual_authority STREQUAL AIRDCCORE_VERSION_AUTHORITY_SHA256)
    message(FATAL_ERROR "Core version authority sha256 mismatch")
  endif()
  if(NOT VERSION STREQUAL "0.0.0" OR NOT TAG_APPLICATION STREQUAL "AirDCCore-macOS" OR
      NOT APPLICATION_ID STREQUAL "org.airdcpp.core.macos.configure")
    message(FATAL_ERROR "unreviewed Core version metadata")
  endif()
  # The sole hash-bound private CMake patch substitutes only version's COMMAND.
  # Do not override a builtin or widen launchers to other custom targets.
  set(expected_command "${PYTHON_EXECUTABLE}" "${AIRDCCORE_VERSION_ADAPTER}" version
    "${AIRDCCORE_VERSION_AUTHORITY}" "${AIRDCCORE_VERSION_AUTHORITY_SHA256}" --
    "${PYTHON_EXECUTABLE}" scripts/generate_version.py ./airdcpp/core/version.inc
    "${VERSION}" "${TAG_APPLICATION}" "${APPLICATION_ID}")
  if(DEFINED AIRDCCORE_VERSION_COMMAND AND NOT "${AIRDCCORE_VERSION_COMMAND}" STREQUAL "" AND
      NOT "${AIRDCCORE_VERSION_COMMAND}" STREQUAL "${expected_command}")
    message(FATAL_ERROR "unreviewed Core version command authority")
  endif()
  set(AIRDCCORE_VERSION_COMMAND "${expected_command}" PARENT_SCOPE)
endfunction()
